### PR TITLE
Example and record types

### PR DESCRIPTION
**Pull request by bartbutenaers**
Hey @xk,
I have added some basic info to your readme page.
Kind regards,
Bart Butenaers

### CODE REVIEW

**Comment by xk** [comment]
Cool, thanks !
Don't you want to add an AUTHORS file with a list with my name and yours, before I merge?
My name by the way is Jorge Chamorro Bieling, jorge@jorgechamorro.com

[EDIT] Never mind I can do that.

**Comment by xk** [comment]
Ohh, one more thing: If you try to get "ANY" off google.com, it returns a list of name servers, not the list of all the records, I don't know why. So perhaps it's not the best example to put in the node's info, no? What do you think?

**Comment by bartbutenaers** [comment]
Hey Jorge,
I'm not at my computer, so cannot test...  No I assume the ANY is not the best example indeed, since you will get many questions from confused users.
Will have a look tonight if you want.

**Comment by xk** [comment]
Don't worry be happy.

**Pull request merged**
